### ISSUE TITLE
link to globus-url-copy is broken in Readme

### ISSUE THREAD

**Issue by riedel** [fr4nk5ch31n3r/gtransfer#49]
see http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/user/#globus-url-copy

seems to be not hosted there anymore. 

https://github.com/globus/globus-toolkit/blob/globus_6_branch/gass/copy/source/globus-url-copy.txt

might be a replacement

**Comment by fscheiner** [comment]
@riedel :
Thanks for the hint, I'll update the README. Since we adopted the Globus Toolkit (GT) as [Grid Community Toolkit (GCT)](https://github.com/gridcf/gct) in the [Grid Community Forum](https://gridcf.org/) we also created a new documentation site located at https://gridcf.org/gct-docs/. This should now be used as the primary source for documentation about the GT - now - GCT.
